/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje2;

import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse.File;
import java.awt.List;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author awada
 */
public class AdminSiparisRaporu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminSiparisRaporu.class.getName());
    private String kullaniciAd;
    private int kullaniciId;

    /**
     * Creates new form AdminSiparisRaporu
     */
    public AdminSiparisRaporu(String ad, int kullaniciID) {
        initComponents();
        this.kullaniciAd = ad;
        this.kullaniciId = kullaniciID;
        TabloYukle();
    }
//DATABASE ILE FRAME ARASINDAKI BAGLANTIYI SAGLAYABILMEK ICIN BIR GETCONNECITON METODU
    private Connection getConnection() {
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/your_database",
    "your_username",
    "your_password"
            );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Bağlantı hatası: " + ex.getMessage());
        }
        return conn;
    }

    private void TabloYukle() {
       // JTable için boş bir model oluşturuluyor ve sütunlar ekleniyor
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("KullaniciID");
    model.addColumn("Kullanici");
    model.addColumn("Cicek");
    model.addColumn("Adet");
    model.addColumn("Toplam");
    model.addColumn("Durum");
    model.addColumn("Tarih");
    
    // Veritabanı bağlantısı açılıyor
    Connection conn = getConnection();
    if (conn == null) {
        return;
    }
    
    try {
        Statement st = conn.createStatement();
        
        // Tüm siparişler kullanıcı ve çiçek bilgileriyle birlikte JOIN ile çekiliyor
        // KullaniciID rapor oluşturmada kullanıcıya göre filtreleme için gerekli
        String sql = "SELECT s.id, s.kullanici_id, k.ad, k.soyad, c.ad as cicek_ad, s.adet, s.toplam_fiyat, s.durum, s.siparis_tarihi FROM siparisler s JOIN kullanicilar k ON s.kullanici_id = k.id JOIN cicekler c ON s.cicek_id = c.id";
        ResultSet rs = st.executeQuery(sql);
        
        // Her satır tabloya ekleniyor
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getInt("kullanici_id"),
                rs.getString("ad") + " " + rs.getString("soyad"),
                rs.getString("cicek_ad"),
                rs.getInt("adet"),
                rs.getInt("toplam_fiyat"),
                rs.getString("durum"),
                rs.getTimestamp("siparis_tarihi")
            });
        }
        
        // Model JTable'a bağlanıyor
        Table.setModel(model);
        st.close();
        conn.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Hata: " + ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        RaporuOlusturButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        RaporuKaydetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        RaporuOlusturButton.setBackground(new java.awt.Color(0, 102, 102));
        RaporuOlusturButton.setForeground(new java.awt.Color(0, 0, 0));
        RaporuOlusturButton.setText("Rapor Olustur");
        RaporuOlusturButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaporuOlusturButtonActionPerformed(evt);
            }
        });

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane2.setViewportView(TextArea);

        RaporuKaydetButton.setBackground(new java.awt.Color(0, 102, 102));
        RaporuKaydetButton.setForeground(new java.awt.Color(0, 0, 0));
        RaporuKaydetButton.setText("Raporu Kaydet");
        RaporuKaydetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaporuKaydetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(RaporuOlusturButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RaporuKaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RaporuKaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RaporuOlusturButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RaporuOlusturButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaporuOlusturButtonActionPerformed
        // Tabloda seçili satırların indeksleri alınıyor
    int[] seciliSatirlar = Table.getSelectedRows();
    
    // Seçili satır var mı kontrolü
    if (seciliSatirlar.length == 0) {
        JOptionPane.showMessageDialog(null, "Lütfen en az bir sipariş seçiniz!", "Hata!", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Rapor içeriği oluşturuluyor
    StringBuilder rapor = new StringBuilder();
    rapor.append("=== SİPARİŞ RAPORU ===\n");
    rapor.append("Tarih: ").append(new java.util.Date()).append("\n\n");
    
    int toplamCiro = 0;
    
    // Seçili her satır için rapor satırı oluşturuluyor
    for (int i : seciliSatirlar) {
        // JTable'dan ilgili kolonların değerleri alınıyor
        int kullaniciId = (int) Table.getValueAt(i, 1);
        String kullanici = Table.getValueAt(i, 2).toString();
        String cicek = Table.getValueAt(i, 3).toString();
        int adet = (int) Table.getValueAt(i, 4);
        int toplam = (int) Table.getValueAt(i, 5);
        String durum = Table.getValueAt(i, 6).toString();
        
        // Toplam ciro hesaplanıyor
        toplamCiro += toplam;
        
        // [kullanici_id:X] formatında satır rapora ekleniyor
        // Bu format User tarafından dosya okunurken filtreleme için kullanılıyor
        rapor.append(String.format("[kullanici_id:%d] %s - %s - %d adet - %d₺ - %s\n",
                kullaniciId, kullanici, cicek, adet, toplam, durum));
    }
    
    // Rapor özeti ekleniyor
    rapor.append("\nToplam Sipariş: ").append(seciliSatirlar.length).append("\n");
    rapor.append("Toplam: ").append(toplamCiro).append("₺\n");
    rapor.append("======================");
    
    // Rapor JTextArea'ya yazılıyor
    TextArea.setText(rapor.toString());
    }//GEN-LAST:event_RaporuOlusturButtonActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TableMouseClicked

    private void RaporuKaydetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaporuKaydetButtonActionPerformed
       // TextArea boş mu kontrolü, rapor oluşturulmadan kaydedilemez
    if (TextArea.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Önce raporu oluşturunuz!", "Hata!", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        // siparis_raporu.txt dosyası açılıyor, true ile mevcut içeriğin üzerine yazmadan sonuna ekleniyor
        BufferedWriter writer = new BufferedWriter(new FileWriter("siparis_raporu.txt", true));
        
        // TextArea'daki rapor içeriği dosyaya yazılıyor
        writer.write(TextArea.getText());
        
        // Bir sonraki rapor için boş satır ekleniyor
        writer.newLine();
        writer.close();
        
        JOptionPane.showMessageDialog(null, "Rapor kaydedildi!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
        
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "Dosya hatası: " + ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_RaporuKaydetButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Çarpıya basılınca AdminAnaSayfa'ya geri dönülüyor
    this.dispose();
    AdminAnaSayfa adminanasayfa = new AdminAnaSayfa(kullaniciAd, kullaniciId);
    adminanasayfa.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminSiparisRaporu("", 0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RaporuKaydetButton;
    private javax.swing.JButton RaporuOlusturButton;
    private javax.swing.JTable Table;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
