/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje2;

import javax.swing.JOptionPane;

/**
 *
 * @author awada
 */
public class AdminAnaSayfa extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminAnaSayfa.class.getName());
    private String Ad;
    private int kullaniciId;

    /**
     * Creates new form AdminAnaSayfa
     */
    public AdminAnaSayfa(String ad, int KullaniciID) {
        initComponents();
        this.Ad = ad;
        this.kullaniciId = KullaniciID;
        //Anasayfada HosGeldiniz mesajini ve giris yapan kisinin adini gosterir 
        HosGeldinizLabel.setText("Hoş Geldiniz " + ad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HosGeldinizLabel = new javax.swing.JLabel();
        CicekEklemeDuzenlemButton = new javax.swing.JButton();
        TeslimatBiligisiButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        SiparisRaporu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        HosGeldinizLabel.setForeground(new java.awt.Color(0, 0, 0));
        HosGeldinizLabel.setText("Hos Geldiniz");

        CicekEklemeDuzenlemButton.setBackground(new java.awt.Color(0, 153, 153));
        CicekEklemeDuzenlemButton.setForeground(new java.awt.Color(0, 0, 0));
        CicekEklemeDuzenlemButton.setText("Cicek Ekleme/Duzenleme");
        CicekEklemeDuzenlemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CicekEklemeDuzenlemButtonActionPerformed(evt);
            }
        });

        TeslimatBiligisiButton.setBackground(new java.awt.Color(0, 153, 153));
        TeslimatBiligisiButton.setForeground(new java.awt.Color(0, 0, 0));
        TeslimatBiligisiButton.setText("Teslimat Bilgisi");
        TeslimatBiligisiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeslimatBiligisiButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cikis Yap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SiparisRaporu.setBackground(new java.awt.Color(0, 153, 153));
        SiparisRaporu.setForeground(new java.awt.Color(0, 0, 0));
        SiparisRaporu.setText("Siparis Raporu");
        SiparisRaporu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiparisRaporuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SiparisRaporu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(HosGeldinizLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CicekEklemeDuzenlemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TeslimatBiligisiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(HosGeldinizLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CicekEklemeDuzenlemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TeslimatBiligisiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SiparisRaporu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CicekEklemeDuzenlemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CicekEklemeDuzenlemButtonActionPerformed
        // Çiçek Ekleme/Düzenleme ekranı açılıyor, admin adı ve id geçiriliyor
        this.dispose();
        ÇiçekEklemeDüzenleme cicekekleduzenle = new ÇiçekEklemeDüzenleme(Ad, kullaniciId);
        cicekekleduzenle.setVisible(true);
    }//GEN-LAST:event_CicekEklemeDuzenlemButtonActionPerformed

    private void TeslimatBiligisiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeslimatBiligisiButtonActionPerformed
        // Admin Teslimat Bilgisi ekranı açılıyor, admin adı ve id geçiriliyor
        this.dispose();
        AdminTeslimatBilgisi teslimatbilgisi = new AdminTeslimatBilgisi(Ad, kullaniciId);
        teslimatbilgisi.setVisible(true);
    }//GEN-LAST:event_TeslimatBiligisiButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Çarpıya basılınca kapanma engelleniyor, uyarı mesajı gösteriliyor
        JOptionPane.showMessageDialog(rootPane, "Cikis Yapmaniz lazim!", "Hata!", JOptionPane.ERROR_MESSAGE);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Çıkış yapmak istediğine dair onay alınıyor
        int onay = JOptionPane.showConfirmDialog(null, "Çıkış yapmak istediğinize emin misiniz?", "Çıkış", JOptionPane.YES_NO_OPTION);
        if (onay == JOptionPane.YES_OPTION) {
            // Onay verilirse Login ekranına dönülüyor
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SiparisRaporuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiparisRaporuActionPerformed
        // Admin Sipariş Raporu ekranı açılıyor, admin adı ve id geçiriliyor
        this.dispose();
        AdminSiparisRaporu adminsiparisraporu = new AdminSiparisRaporu(Ad, kullaniciId);
        adminsiparisraporu.setVisible(true);
    }//GEN-LAST:event_SiparisRaporuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminAnaSayfa("", 0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CicekEklemeDuzenlemButton;
    private javax.swing.JLabel HosGeldinizLabel;
    private javax.swing.JButton SiparisRaporu;
    private javax.swing.JButton TeslimatBiligisiButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
