/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author awada
 */
public class AdminTeslimatBilgisi extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminTeslimatBilgisi.class.getName());
    private String kullaniciAd;
    private int kullaniciID;
    private int seciliSiparisId = -1;

    /**
     * Creates new form TeslimatBilgisi
     */
    public AdminTeslimatBilgisi(String ad, int kullaniciId) {
        initComponents();
        this.kullaniciAd = ad;
        this.kullaniciID = kullaniciId;
        TabloYukle();
    }
//DATABASE ILE FRAME ARASINDAKI BAGLANTIYI SAGLAYABILMEK ICIN BIR GETCONNECITON METODU
    private Connection getConnection() {
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/your_database",
    "your_username",
    "your_password"
            );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Bağlantı hatası: " + ex.getMessage());
        }
        return conn;
    }

    private void TabloYukle() {
        // JTable için boş bir model oluşturuluyor ve sütunlar ekleniyor
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("KullaniciID");
    model.addColumn("Kullanici");
    model.addColumn("Cicek");
    model.addColumn("Adet");
    model.addColumn("Toplam");
    model.addColumn("Odeme");
    model.addColumn("Durum");
    model.addColumn("Tarih");
    
    // Veritabanı bağlantısı açılıyor
    Connection conn = getConnection();
    if (conn == null) {
        return;
    }
    
    try {
        Statement st = conn.createStatement();
        
        // Tüm siparişler kullanıcı ve çiçek bilgileriyle birlikte JOIN ile çekiliyor
        String sql = "SELECT s.id, s.kullanici_id, k.ad, k.soyad, c.ad as cicek_ad, s.adet, s.toplam_fiyat, s.odeme_yontemi, s.durum, s.siparis_tarihi FROM siparisler s JOIN kullanicilar k ON s.kullanici_id = k.id JOIN cicekler c ON s.cicek_id = c.id";
        ResultSet rs = st.executeQuery(sql);
        
        // Her satır tabloya ekleniyor
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getInt("kullanici_id"),
                rs.getString("ad") + " " + rs.getString("soyad"),
                rs.getString("cicek_ad"),
                rs.getInt("adet"),
                rs.getInt("toplam_fiyat"),
                rs.getString("odeme_yontemi"),
                rs.getString("durum"),
                rs.getTimestamp("siparis_tarihi")
            });
        }
        
        // Model JTable'a bağlanıyor
        Table.setModel(model);
        st.close();
        conn.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Hata: " + ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        TeslimatDurumuComboBox = new javax.swing.JComboBox<>();
        GuncelleButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        TeslimatDurumuComboBox.setForeground(new java.awt.Color(0, 0, 0));
        TeslimatDurumuComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hazirlaniyor", "Kargoya Verildi", "Teslim Edildi", "Iptal Edildi" }));
        TeslimatDurumuComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeslimatDurumuComboBoxActionPerformed(evt);
            }
        });

        GuncelleButton.setBackground(new java.awt.Color(0, 102, 102));
        GuncelleButton.setForeground(new java.awt.Color(0, 0, 0));
        GuncelleButton.setText("Guncelle");
        GuncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuncelleButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(70, 73, 75));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Teslimat Durmu:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GuncelleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeslimatDurumuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeslimatDurumuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GuncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Çarpıya basılınca AdminAnaSayfa'ya geri dönülüyor
    this.dispose();
    AdminAnaSayfa adminAnaSayfa = new AdminAnaSayfa(kullaniciAd, kullaniciID);
    adminAnaSayfa.setVisible(true);

    }//GEN-LAST:event_formWindowClosing

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // Tıklanan satırın indeksi alınıyor
    int row = Table.getSelectedRow();
    
    if (row != -1) {
        // Seçili siparişin ID'si saklanıyor, güncelleme işleminde kullanılacak
        seciliSiparisId = (int) Table.getValueAt(row, 0);
    }
            
    }//GEN-LAST:event_TableMouseClicked

    private void GuncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuncelleButtonActionPerformed
        try {
        // Seçili sipariş var mı kontrolü, yoksa özel exception fırlatılıyor
        if (seciliSiparisId == -1) {
            throw new SiparisException("Lütfen bir sipariş seçiniz!");
        }
        
        // ComboBox'tan seçilen yeni teslimat durumu alınıyor
        String Durum = TeslimatDurumuComboBox.getSelectedItem().toString();
        
        // Veritabanı bağlantısı açılıyor
        Connection conn = getConnection();
        if (conn == null) return;
        
        Statement st = conn.createStatement();
        
        // Seçili siparişin durumu veritabanında güncelleniyor
        String sql = String.format("UPDATE siparisler SET durum='%s' WHERE id=%d", Durum, seciliSiparisId);
        st.executeUpdate(sql);
        
        JOptionPane.showMessageDialog(null, "Teslimat durumu güncellendi!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
        
        // Tablo güncelleniyor ve seçili sipariş ID'si sıfırlanıyor
        TabloYukle();
        seciliSiparisId = -1;
        st.close();
        conn.close();
        
    } catch (SiparisException ex) {
        // Özel exception yakalanıyor ve hata mesajı gösteriliyor
        JOptionPane.showMessageDialog(null, ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Veritabanı hatası: " + ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_GuncelleButtonActionPerformed

    private void TeslimatDurumuComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeslimatDurumuComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeslimatDurumuComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminTeslimatBilgisi("", 0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuncelleButton;
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> TeslimatDurumuComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
