/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author awada
 */
public class KatalogGörüntüleme extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KatalogGörüntüleme.class.getName());
    private String kullaniciAd;
    private int seciliCicekId = -1;
    private int kullaniciId;

    /**
     * Creates new form KatalogGörüntüleme
     */
    public KatalogGörüntüleme(String ad, int kullaniciID) {
        initComponents();

        this.kullaniciAd = ad;
        this.kullaniciId = kullaniciID;
        TabloYukle();

    }

    //DATABASE ILE FRAME ARASINDAKI BAGLANTIYI SAGLAYABILMEK ICIN BIR GETCONNECITON METODU
    private Connection getConnection() {
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(
                   "jdbc:mysql://localhost:3306/your_database",
    "your_username",
    "your_password"
            );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Bağlantı hatası: " + ex.getMessage());
        }
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AramaTextField = new javax.swing.JTextField();
        TumKategorilerComboBox = new javax.swing.JComboBox<>();
        TumRenklerComboBox = new javax.swing.JComboBox<>();
        StoktaOlanlarChcekBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Panel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AdLabel = new javax.swing.JLabel();
        KategoriLabel = new javax.swing.JLabel();
        RenkLabel = new javax.swing.JLabel();
        FiyatLabel = new javax.swing.JLabel();
        StokLabel = new javax.swing.JLabel();
        TurLabel = new javax.swing.JLabel();
        MevsimlikLabel = new javax.swing.JLabel();
        IthalLabel = new javax.swing.JLabel();
        KokuluLabel = new javax.swing.JLabel();
        AciklamaLabel = new javax.swing.JLabel();
        SiparisVerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Arama:");

        AramaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AramaTextFieldKeyReleased(evt);
            }
        });

        TumKategorilerComboBox.setForeground(new java.awt.Color(0, 0, 0));
        TumKategorilerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tum Kategoriler", "Gül", "Lale", "Papatya", "Orkide" }));
        TumKategorilerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TumKategorilerComboBoxActionPerformed(evt);
            }
        });

        TumRenklerComboBox.setForeground(new java.awt.Color(0, 0, 0));
        TumRenklerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tum Renkler", "Sarı", "Kırmızı", "Beyaz", "Pembe", "Mavi", "Siyah" }));
        TumRenklerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TumRenklerComboBoxActionPerformed(evt);
            }
        });

        StoktaOlanlarChcekBox.setForeground(new java.awt.Color(0, 0, 0));
        StoktaOlanlarChcekBox.setText("Stokta Olanlar");
        StoktaOlanlarChcekBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoktaOlanlarChcekBoxActionPerformed(evt);
            }
        });

        Table.setForeground(new java.awt.Color(0, 0, 0));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        Panel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ad:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Kategori:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Renk:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fiyat:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Stok:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tur:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Mevsimlik:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Ithal:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Kokulu:");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Aciklama:");

        AdLabel.setForeground(new java.awt.Color(0, 0, 0));

        KategoriLabel.setForeground(new java.awt.Color(0, 0, 0));

        RenkLabel.setForeground(new java.awt.Color(0, 0, 0));

        FiyatLabel.setForeground(new java.awt.Color(0, 0, 0));

        StokLabel.setForeground(new java.awt.Color(0, 0, 0));

        TurLabel.setForeground(new java.awt.Color(0, 0, 0));

        MevsimlikLabel.setForeground(new java.awt.Color(0, 0, 0));

        IthalLabel.setForeground(new java.awt.Color(0, 0, 0));

        KokuluLabel.setForeground(new java.awt.Color(0, 0, 0));

        AciklamaLabel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)))
                .addGap(25, 25, 25)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KategoriLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(AdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RenkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FiyatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StokLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MevsimlikLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IthalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KokuluLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AciklamaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(KategoriLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RenkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiyatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(StokLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MevsimlikLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(IthalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(KokuluLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(AciklamaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        SiparisVerButton.setBackground(new java.awt.Color(0, 102, 102));
        SiparisVerButton.setForeground(new java.awt.Color(0, 0, 0));
        SiparisVerButton.setText("Siparis Ver");
        SiparisVerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiparisVerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AramaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TumKategorilerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TumRenklerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(StoktaOlanlarChcekBox)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SiparisVerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AramaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TumKategorilerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TumRenklerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StoktaOlanlarChcekBox))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SiparisVerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void TabloYukle() {
        // JTable için boş bir model oluşturuluyor ve sütunlar ekleniyor
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Ad");
        model.addColumn("Kategori");
        model.addColumn("Renk");
        model.addColumn("Fiyat");
        model.addColumn("Stok");
        model.addColumn("Tur");

        // Veritabanı bağlantısı açılıyor
        Connection conn = getConnection();
        if (conn == null) {
            return;
        }

        try {
            Statement st = conn.createStatement();

            // Tüm çiçekler veritabanından çekiliyor
            String sql = "SELECT * FROM cicekler";
            ResultSet rs = st.executeQuery(sql);

            // Her satır tabloya ekleniyor
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("ad"),
                    rs.getString("kategori"),
                    rs.getString("renk"),
                    rs.getDouble("fiyat"),
                    rs.getInt("stok"),
                    rs.getString("tur")
                });
            }

            // Model JTable'a bağlanıyor
            Table.setModel(model);
            conn.close();
            st.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Hata: " + ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Çarpıya basılınca UserAnaSayfa'ya geri dönülüyor
        UserAnaSayfa anasayfa = new UserAnaSayfa(kullaniciAd, kullaniciId);
        anasayfa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // Tıklanan satırın indeksi alınıyor
        int row = Table.getSelectedRow();

        if (row != -1) {
            // Seçili çiçeğin ID'si saklanıyor, sipariş işleminde kullanılacak
            int id = (int) Table.getValueAt(row, 0);
            seciliCicekId = id;

            // Tablodaki veriler sağdaki detay labellarına aktarılıyor
            AdLabel.setText(Table.getValueAt(row, 1).toString());
            KategoriLabel.setText(Table.getValueAt(row, 2).toString());
            RenkLabel.setText(Table.getValueAt(row, 3).toString());
            FiyatLabel.setText(Table.getValueAt(row, 4).toString());
            StokLabel.setText(Table.getValueAt(row, 5).toString());
            TurLabel.setText(Table.getValueAt(row, 6).toString());

            // Veritabanı bağlantısı açılıyor
            Connection conn = getConnection();
            if (conn == null) {
                return;
            }

            try {
                Statement st = conn.createStatement();

                // Tabloda görünmeyen özellikler DB'den çekiliyor
                String sql = String.format("SELECT mevsimlik, ithal, kokulu, aciklama FROM cicekler WHERE id=%d", id);
                ResultSet rs = st.executeQuery(sql);

                if (rs.next()) {
                    // Boolean değerler "Evet"/"Hayir" olarak gösteriliyor
                    MevsimlikLabel.setText(rs.getBoolean("mevsimlik") ? "Evet" : "Hayir");
                    IthalLabel.setText(rs.getBoolean("ithal") ? "Evet" : "Hayir");
                    KokuluLabel.setText(rs.getBoolean("kokulu") ? "Evet" : "Hayir");
                    AciklamaLabel.setText(rs.getString("aciklama"));
                }
                st.close();
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Hata: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_TableMouseClicked
    private void TabloFiltrele() {
        // Arama ve filtre alanlarından değerler alınıyor
        String arama = AramaTextField.getText().trim();
        String kategori = TumKategorilerComboBox.getSelectedItem().toString();
        String renk = TumRenklerComboBox.getSelectedItem().toString();

        // JTable için boş bir model oluşturuluyor ve sütunlar ekleniyor
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Ad");
        model.addColumn("Kategori");
        model.addColumn("Renk");
        model.addColumn("Fiyat");
        model.addColumn("Stok");
        model.addColumn("Tur");

        // Veritabanı bağlantısı açılıyor
        Connection conn = getConnection();
        if (conn == null) {
            return;
        }

        try {
            Statement st = conn.createStatement();

            // Temel SQL sorgusu: adında arama metnini içeren çiçekler
            String sql = String.format("SELECT * FROM cicekler WHERE ad LIKE '%%%s%%'", arama);

            // Kategori filtresi seçildiyse SQL'e ekleniyor
            if (!kategori.equals("Tum Kategoriler")) {
                sql += String.format(" AND kategori='%s'", kategori);
            }

            // Renk filtresi seçildiyse SQL'e ekleniyor
            if (!renk.equals("Tum Renkler")) {
                sql += String.format(" AND renk='%s'", renk);
            }

            // Stokta olanlar filtresi seçildiyse SQL'e ekleniyor
            if (StoktaOlanlarChcekBox.isSelected()) {
                sql += " AND stok>0";
            }

            ResultSet rs = st.executeQuery(sql);

            // Filtrelenmiş sonuçlar tabloya ekleniyor
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("ad"),
                    rs.getString("kategori"),
                    rs.getString("Renk"),
                    rs.getDouble("fiyat"),
                    rs.getInt("stok"),
                    rs.getString("tur")
                });
            }

            // Model JTable'a bağlanıyor
            Table.setModel(model);
            conn.close();
            st.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Hata: " + ex.getMessage());
        }
    }
    private void AramaTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AramaTextFieldKeyReleased
        TabloFiltrele();
    }//GEN-LAST:event_AramaTextFieldKeyReleased

    private void TumKategorilerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TumKategorilerComboBoxActionPerformed
        TabloFiltrele();
    }//GEN-LAST:event_TumKategorilerComboBoxActionPerformed

    private void TumRenklerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TumRenklerComboBoxActionPerformed
        TabloFiltrele();
    }//GEN-LAST:event_TumRenklerComboBoxActionPerformed

    private void StoktaOlanlarChcekBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoktaOlanlarChcekBoxActionPerformed
        TabloFiltrele();
    }//GEN-LAST:event_StoktaOlanlarChcekBoxActionPerformed

    private void SiparisVerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiparisVerButtonActionPerformed

        // Tabloda seçili bir çiçek var mı kontrolü, -1 ise seçili yok demek
        if (seciliCicekId == -1) {
            JOptionPane.showMessageDialog(null, "Lütfen bir çiçek seçiniz!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Sipariş Oluşturma ekranı açılıyor, kullanıcı adı, seçili çiçek ID'si ve kullanıcı ID'si geçiriliyor
        SiparisOlusturma siparisOlusturma = new SiparisOlusturma(kullaniciAd, seciliCicekId, kullaniciId);
        siparisOlusturma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SiparisVerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KatalogGörüntüleme("", 0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AciklamaLabel;
    private javax.swing.JLabel AdLabel;
    private javax.swing.JTextField AramaTextField;
    private javax.swing.JLabel FiyatLabel;
    private javax.swing.JLabel IthalLabel;
    private javax.swing.JLabel KategoriLabel;
    private javax.swing.JLabel KokuluLabel;
    private javax.swing.JLabel MevsimlikLabel;
    private javax.swing.JPanel Panel2;
    private javax.swing.JLabel RenkLabel;
    private javax.swing.JButton SiparisVerButton;
    private javax.swing.JLabel StokLabel;
    private javax.swing.JCheckBox StoktaOlanlarChcekBox;
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> TumKategorilerComboBox;
    private javax.swing.JComboBox<String> TumRenklerComboBox;
    private javax.swing.JLabel TurLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
