/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author awada
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    private int kullaniciId;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

    }
//DATABASE ILE FRAME ARASINDAKI BAGLANTIYI SAGLAYABILMEK ICIN BIR GETCONNECITON METODU

    private Connection getConnection() {
        Connection conn = null;
        try {

            conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/cicek_sistemi",
                    "root",
                    "Awadj40xz321"
            );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database connection error: " + ex.getMessage());
        }
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        AdminGirisYapButton = new javax.swing.JButton();
        AdminIptalEtButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AdminEPostatextField = new javax.swing.JTextField();
        AdminSifreTexrfield = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserEpostaTextField = new javax.swing.JTextField();
        UserSifreTextfield = new javax.swing.JTextField();
        UserIptalEtButton = new javax.swing.JButton();
        UserGirisYapButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        AdminGirisYapButton.setText("Giris Yap");
        AdminGirisYapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminGirisYapButtonActionPerformed(evt);
            }
        });

        AdminIptalEtButton.setText("Iptal Et");
        AdminIptalEtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminIptalEtButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("E-Posta:");

        jLabel2.setText("Sifre:");

        AdminEPostatextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminEPostatextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(AdminIptalEtButton)
                        .addGap(36, 36, 36)
                        .addComponent(AdminGirisYapButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AdminSifreTexrfield, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(AdminEPostatextField))))
                .addGap(0, 95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AdminEPostatextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(AdminSifreTexrfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminIptalEtButton)
                    .addComponent(AdminGirisYapButton))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setText("E-posta:");

        jLabel4.setText("Sifre:");

        UserIptalEtButton.setText("Iptal et");
        UserIptalEtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIptalEtButtonActionPerformed(evt);
            }
        });

        UserGirisYapButton.setText("Giris Yap");
        UserGirisYapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserGirisYapButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserEpostaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(UserSifreTextfield)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(UserIptalEtButton)
                        .addGap(39, 39, 39)
                        .addComponent(UserGirisYapButton)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserEpostaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(UserSifreTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIptalEtButton)
                    .addComponent(UserGirisYapButton))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminGirisYapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminGirisYapButtonActionPerformed
        // Admin e-posta ve şifre alanlarından girilen değerler alınıyor
        String EPosta = AdminEPostatextField.getText().trim();
        String Sifre = AdminSifreTexrfield.getText().trim();

        // Boş alan kontrolü
        if (EPosta.isEmpty() || Sifre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Verilen alanlardan birini bos biraktiniz!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Veritabanı bağlantısı açılıyor
        Connection conn = getConnection();
        if (conn == null) {
            return;
        }

        try {
            Statement st = conn.createStatement();

            // BINARY ile büyük/küçük harf duyarlı e-posta ve şifre kontrolü
            String sql = String.format("SELECT * FROM kullanicilar WHERE BINARY eposta = '%s' AND BINARY sifre = '%s'", EPosta, Sifre);
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String ad = rs.getString("ad");

                // Kullanıcının rolü kontrol ediliyor
                String rol = rs.getString("rol");
                int id = rs.getInt("id");

                if (rol.equals("admin")) {
                    // Admin ise AdminAnaSayfa açılıyor
                    JOptionPane.showMessageDialog(null, "Giris Basarili!", "Basarili", JOptionPane.INFORMATION_MESSAGE);
                    AdminAnaSayfa adminAnaSayfa = new AdminAnaSayfa(ad, id);
                    adminAnaSayfa.setVisible(true);
                    this.dispose();
                } else {
                    // Admin değilse hata mesajı
                    JOptionPane.showMessageDialog(null, "Admin yetkisi yok!", "Hata!", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Alanlar temizleniyor
                AdminEPostatextField.setText("");
                AdminSifreTexrfield.setText("");

            } else {
                JOptionPane.showMessageDialog(null, "E-Posta veya sifre yanlis!", "Hata!", JOptionPane.WARNING_MESSAGE);
            }

            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Veritabani hatasi: " + ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AdminGirisYapButtonActionPerformed

    private void AdminIptalEtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminIptalEtButtonActionPerformed
        // Admin iptal butonuna basılınca Register ekranına geri dönülüyor
        Register register = new Register();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdminIptalEtButtonActionPerformed

    private void UserGirisYapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserGirisYapButtonActionPerformed
        // Kullanıcının girdiği e-posta ve şifre alınıyor
        String EPosta = UserEpostaTextField.getText().trim();
        String Sifre = UserSifreTextfield.getText().trim();

        // Boş alan kontrolü
        if (EPosta.isEmpty() || Sifre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Verilen alanlardan birini bos biraktiniz!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Veritabanı bağlantısı açılıyor
        Connection conn = getConnection();
        if (conn == null) {
            return;
        }

        try {
            Statement st = conn.createStatement();

            // BINARY ile büyük/küçük harf duyarlı e-posta ve şifre kontrolü
            String sql = String.format("SELECT * FROM kullanicilar WHERE BINARY eposta = '%s' AND BINARY sifre = '%s'", EPosta, Sifre);
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                // Kullanıcı bilgileri alınıyor
                String ad = rs.getString("ad");
                int id = rs.getInt("id");

                JOptionPane.showMessageDialog(null, "Giris Basarili!", "Basarili", JOptionPane.INFORMATION_MESSAGE);

                // Alanlar temizleniyor
                UserEpostaTextField.setText("");
                UserSifreTextfield.setText("");

                // UserAnaSayfa açılıyor, kullanıcı adı ve id geçiriliyor
                UserAnaSayfa anasayfa = new UserAnaSayfa(ad, id);
                anasayfa.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "E-Posta veya sifre yanlis!", "Hata!", JOptionPane.WARNING_MESSAGE);
            }

            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Veritabani hatasi: " + ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UserGirisYapButtonActionPerformed

    private void UserIptalEtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIptalEtButtonActionPerformed
        // User iptal butonuna basılınca Register ekranına geri dönülüyor
        Register register = new Register();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserIptalEtButtonActionPerformed

    private void AdminEPostatextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminEPostatextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminEPostatextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdminEPostatextField;
    private javax.swing.JButton AdminGirisYapButton;
    private javax.swing.JButton AdminIptalEtButton;
    private javax.swing.JTextField AdminSifreTexrfield;
    private javax.swing.JTextField UserEpostaTextField;
    private javax.swing.JButton UserGirisYapButton;
    private javax.swing.JButton UserIptalEtButton;
    private javax.swing.JTextField UserSifreTextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
