/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author awada
 */
public class Register extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());
    private int kullaniciId;

    /**
     * Creates new form RegisterLogin
     */
    public Register() {
        initComponents();

    }

    //DATABASE ILE FRAME ARASINDAKI BAGLANTIYI SAGLAYABILMEK ICIN BIR GETCONNECITON METODU
    private Connection getConnection() {
        Connection conn = null;
        try {

            conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/cicek_sistemi",
                    "root",
                    "Awadj40xz321"
            );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database connection error: " + ex.getMessage());
        }
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KayitOlPanel = new javax.swing.JPanel();
        KayitOlButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AdTextField = new javax.swing.JTextField();
        SoyadTextField = new javax.swing.JTextField();
        EPostaTextField = new javax.swing.JTextField();
        SifreTextField = new javax.swing.JTextField();
        TekrarSifreTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        KayitOlPanel.setBackground(new java.awt.Color(51, 51, 51));

        KayitOlButton.setText("Kayit Ol");
        KayitOlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KayitOlButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ad:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soyad:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-Posta:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sifre:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tekrar Sifre:");

        EPostaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPostaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KayitOlPanelLayout = new javax.swing.GroupLayout(KayitOlPanel);
        KayitOlPanel.setLayout(KayitOlPanelLayout);
        KayitOlPanelLayout.setHorizontalGroup(
            KayitOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KayitOlPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(KayitOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KayitOlPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TekrarSifreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                    .addGroup(KayitOlPanelLayout.createSequentialGroup()
                        .addGroup(KayitOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(KayitOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SoyadTextField)
                            .addComponent(AdTextField)))
                    .addGroup(KayitOlPanelLayout.createSequentialGroup()
                        .addGroup(KayitOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KayitOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SifreTextField)
                            .addComponent(EPostaTextField))))
                .addGap(127, 127, 127))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KayitOlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KayitOlButton)
                .addGap(155, 155, 155))
        );
        KayitOlPanelLayout.setVerticalGroup(
            KayitOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KayitOlPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(KayitOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(KayitOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SoyadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(KayitOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EPostaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(KayitOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SifreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(KayitOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TekrarSifreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(KayitOlButton)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(KayitOlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(KayitOlPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KayitOlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KayitOlButtonActionPerformed
        // Kullanıcının girdiği bilgileri alıyoruz
        String Ad = AdTextField.getText().trim();
        String Soyad = SoyadTextField.getText().trim();
        String EPosta = EPostaTextField.getText().trim();
        String Sifre = SifreTextField.getText().trim();
        String TekrarSifre = TekrarSifreTextField.getText().trim();

        // Boş alan kontrolü
        if (Ad.isEmpty() || Soyad.isEmpty() || EPosta.isEmpty() || Sifre.isEmpty() || TekrarSifre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Verilen alanlardan birini bos biraktiniz!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Şifre regex kontrolü: en az 6 karakter, bir büyük harf, bir rakam
        Pattern pattern = Pattern.compile("^(?=.*[A-Z])(?=.*[0-9]).{6,}$");
        Matcher match = pattern.matcher(Sifre);
        if (!match.find()) {
            JOptionPane.showMessageDialog(null, "Sifre en az 6 karakter, bir buyuk harf ve bir rakam icermelidir!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Şifre eşleşme kontrolü
        if (!Sifre.equals(TekrarSifre)) {
            JOptionPane.showMessageDialog(null, "Sifreler uyusmuyor!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // E-posta regex kontrolü
        Pattern epostaPattern = Pattern.compile("^[\\w.%+-]+@[a-zA-Z0-9.-]+\\.[a-z]{2,}$");
        Matcher epostaMatch = epostaPattern.matcher(EPosta);
        if (!epostaMatch.find()) {
            JOptionPane.showMessageDialog(null, "EPosta gecersiz!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Veritabanı bağlantısı açılıyor
        Connection conn = getConnection();
        if (conn == null) {
            return;
        }

        try {
            Statement st = conn.createStatement();

            // E-posta daha önce kayıtlı mı kontrol ediliyor
            String sql = String.format("SELECT eposta FROM kullanicilar WHERE eposta='%s' ", EPosta);
            ResultSet k = st.executeQuery(sql);
            if (k.next()) {
                JOptionPane.showMessageDialog(null, "Bu E-Posta zaten kayitli!", "Hata!", JOptionPane.ERROR_MESSAGE);
                conn.close();
                return;
            }

            // Yeni kullanıcı veritabanına ekleniyor
            String SQL = String.format("INSERT INTO kullanicilar (ad, soyad, eposta, sifre, bakiye) VALUES ('%s', '%s', '%s', '%s', 0.0)",
                    Ad, Soyad, EPosta, Sifre);
            st.executeUpdate(SQL);

            JOptionPane.showMessageDialog(null, "Kayit basarili!", "Basarili", JOptionPane.INFORMATION_MESSAGE);

            // Alanlar temizleniyor
            AdTextField.setText("");
            SoyadTextField.setText("");
            EPostaTextField.setText("");
            SifreTextField.setText("");
            TekrarSifreTextField.setText("");

            // Login ekranına geçiliyor
            Login login = new Login();
            login.setVisible(true);
            this.dispose();

            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Veritabani hatasi: " + ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_KayitOlButtonActionPerformed

    private void EPostaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPostaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPostaTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdTextField;
    private javax.swing.JTextField EPostaTextField;
    private javax.swing.JButton KayitOlButton;
    private javax.swing.JPanel KayitOlPanel;
    private javax.swing.JTextField SifreTextField;
    private javax.swing.JTextField SoyadTextField;
    private javax.swing.JTextField TekrarSifreTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
