/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje2;

import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author awada
 */
public class SiparisOlusturma extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SiparisOlusturma.class.getName());
    DefaultListModel<String> model = new DefaultListModel<>();

    private String kullaniciAd;
    private int seciliCicekId;
    private double cicekfiyati = 0.0;
    private int kullaniciId;
    /**
     * Creates new form SiparisOlusturma
     */
    public SiparisOlusturma(String Ad, int CicekID, int kullaniciID) {
        initComponents();
        List.setModel(model);
        this.kullaniciAd = Ad;
        this.seciliCicekId = CicekID;
        this.kullaniciId = kullaniciID;

        CicekBilgileriniYukle();
    }
//DATABASE ILE FRAME ARASINDAKI BAGLANTIYI SAGLAYABILMEK ICIN BIR GETCONNECITON METODU
    private Connection getConnection() {
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(
                   "jdbc:mysql://localhost:3306/your_database",
    "your_username",
    "your_password"
            );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Bağlantı hatası: " + ex.getMessage());
        }
        return conn;
    }

    private void CicekBilgileriniYukle() {
        // Veritabanı bağlantısı açılıyor
    Connection conn = getConnection();
    if (conn == null) {
        return;
    }
    
    try {
        Statement st = conn.createStatement();
        
        // Seçili çiçeğin bilgileri ID'ye göre veritabanından çekiliyor
        String sql = String.format("SELECT * FROM cicekler WHERE id=%d", seciliCicekId);
        ResultSet rs = st.executeQuery(sql);
        
        while (rs.next()) {
            // Renk ve kategori bilgisi birleştirilerek label'a yazılıyor
            RenkveKategoriLabel.setText(rs.getString("renk") + " " + rs.getString("kategori"));
            
            // Fiyat alınıyor ve ilgili label'lara yazılıyor
            cicekfiyati = rs.getInt("fiyat");
            FiyatLabel.setText(cicekfiyati + "₺");
            ToplamLabel.setText("Toplam: " + cicekfiyati + " ₺");
            
            // Stok bilgisine göre AdetSpinner'ın maksimum değeri ayarlanıyor
            // Kullanıcı stoktan fazla adet giremez
            int stok = rs.getInt("stok");
            AdetSpinner.setModel(new SpinnerNumberModel(1, 1, stok, 1));
        }
        st.close();
        conn.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Hata: " + ex.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RenkveKategoriLabel = new javax.swing.JLabel();
        FiyatLabel = new javax.swing.JLabel();
        AdetSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TeslimatAdresiTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TelefonTextField = new javax.swing.JTextField();
        HizliTeslimatCheckBox = new javax.swing.JCheckBox();
        SpeteEkleButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();
        Panel2 = new javax.swing.JPanel();
        Toplamlabel = new javax.swing.JLabel();
        SiparisiKaldirButton = new javax.swing.JButton();
        SipariTamamlaButton = new javax.swing.JButton();
        Panel1 = new javax.swing.JPanel();
        ToplamLabel = new javax.swing.JLabel();
        OdemeYontemiComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Panel.setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Secilen Cicek:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fiyat:");

        RenkveKategoriLabel.setForeground(new java.awt.Color(0, 0, 0));

        FiyatLabel.setForeground(new java.awt.Color(0, 0, 0));

        AdetSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 0, 100, 1));
        AdetSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AdetSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AdetSpinnerStateChanged(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Adet:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Teslimat Adresi:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telefon:");

        HizliTeslimatCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        HizliTeslimatCheckBox.setText("Hizli Teslimat");

        SpeteEkleButton.setBackground(new java.awt.Color(0, 102, 102));
        SpeteEkleButton.setForeground(new java.awt.Color(0, 0, 0));
        SpeteEkleButton.setText("SPETE EKLE");
        SpeteEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeteEkleButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(List);

        Panel2.setBackground(new java.awt.Color(0, 153, 153));

        Toplamlabel.setForeground(new java.awt.Color(0, 0, 0));
        Toplamlabel.setText("Toplam: 0");

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Toplamlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(Toplamlabel)
                .addContainerGap())
        );

        SiparisiKaldirButton.setBackground(new java.awt.Color(153, 0, 0));
        SiparisiKaldirButton.setForeground(new java.awt.Color(0, 0, 0));
        SiparisiKaldirButton.setText("Secileni Kaldir");
        SiparisiKaldirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiparisiKaldirButtonActionPerformed(evt);
            }
        });

        SipariTamamlaButton.setBackground(new java.awt.Color(0, 153, 0));
        SipariTamamlaButton.setForeground(new java.awt.Color(0, 0, 0));
        SipariTamamlaButton.setText("Siparisi Tamamla");
        SipariTamamlaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SipariTamamlaButtonActionPerformed(evt);
            }
        });

        Panel1.setBackground(new java.awt.Color(0, 153, 153));

        ToplamLabel.setForeground(new java.awt.Color(0, 0, 0));
        ToplamLabel.setText("Toplam:");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ToplamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(ToplamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        OdemeYontemiComboBox.setForeground(new java.awt.Color(0, 0, 0));
        OdemeYontemiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kredi Kart", "Nakit", "Havale" }));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Odeme Yontemi:");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AdetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(TeslimatAdresiTextField)
                        .addComponent(jLabel5)
                        .addComponent(TelefonTextField)
                        .addComponent(SpeteEkleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RenkveKategoriLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(FiyatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(HizliTeslimatCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(OdemeYontemiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SiparisiKaldirButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SipariTamamlaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(RenkveKategoriLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FiyatLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TeslimatAdresiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TelefonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OdemeYontemiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(HizliTeslimatCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SpeteEkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SiparisiKaldirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SipariTamamlaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SipariTamamlaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SipariTamamlaButtonActionPerformed

        // Teslimat adresi, telefon, ödeme yöntemi ve hızlı teslimat bilgileri alınıyor
    String adres = TeslimatAdresiTextField.getText().trim();
    String telefon = TelefonTextField.getText().trim();
    String odeme = OdemeYontemiComboBox.getSelectedItem().toString();
    boolean hizliTeslimat = HizliTeslimatCheckBox.isSelected();
    
    // Sepet boş mu kontrolü
    if (model.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Sepet boş!", "Hata!", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Veritabanı bağlantısı açılıyor
    Connection conn = getConnection();
    if (conn == null) {
        return;
    }
    
    try {
        Statement st = conn.createStatement();
        
        // Sepetteki her ürün için sipariş kaydediliyor
        for (int i = 0; i < model.size(); i++) {
            String item = model.elementAt(i);
            
            // JList'teki metin "->" ile bölünüyor, toplam fiyat alınıyor
            String[] parca = item.split("->");
            int ToplamMiktar = (int) Double.parseDouble(parca[1].trim());
            
            // Adet bilgisi "x" ile bölünerek alınıyor
            String[] YeniParca = parca[0].split("x");
            int adet = (int) Double.parseDouble(YeniParca[1]);
            
            // Sipariş veritabanına kaydediliyor
            String sql = String.format(
                "INSERT INTO siparisler(kullanici_id, cicek_id, adet, toplam_fiyat, teslimat_adresi, telefon, odeme_yontemi, hizli_teslimat) VALUES (%d, %d, %d, %d, '%s', '%s', '%s', %b)",
                kullaniciId, seciliCicekId, adet, (int) ToplamMiktar, adres, telefon, odeme, hizliTeslimat);
            st.executeUpdate(sql);
            
            // Sipariş verilen çiçeğin stoku güncelleniyor
            String StokGuncelle = String.format("UPDATE cicekler SET stok=stok - %d WHERE id=%d", adet, seciliCicekId);
            st.executeUpdate(StokGuncelle);
        }
        
        JOptionPane.showMessageDialog(null, "Sipariş başarıyla tamamlandı!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
        st.close();
        conn.close();
        
        // UserAnaSayfa'ya geri dönülüyor
        UserAnaSayfa anasayfa = new UserAnaSayfa(kullaniciAd, kullaniciId);
        anasayfa.setVisible(true);
        this.dispose();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Hata: " + ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_SipariTamamlaButtonActionPerformed

    private void AdetSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AdetSpinnerStateChanged
        // Spinner değeri değişince toplam fiyat güncelleniyor
    int adet = (int) AdetSpinner.getValue();
    ToplamLabel.setText("Toplam:" + adet * cicekfiyati + "₺");
    }//GEN-LAST:event_AdetSpinnerStateChanged

    private void SpeteEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeteEkleButtonActionPerformed
       // Adres, telefon ve adet bilgileri alınıyor
    String adres = TeslimatAdresiTextField.getText().trim();
    String telefon = TelefonTextField.getText().trim();
    int adet = (int) AdetSpinner.getValue();
    double toplam = adet * cicekfiyati;
    String cicekadi = RenkveKategoriLabel.getText();
    
    // JList'e eklenecek sepet satırı oluşturuluyor
    String SepetListesi = cicekadi + "x" + adet + "->" + toplam;
    
    // Adres ve telefon boş alan kontrolü
    if (adres.isEmpty() || telefon.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Adres veya telefon boş olamaz!", "Hata!", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Telefon regex kontrolü: 05 ile başlamalı ve 11 haneli olmalı
    Pattern telefonPattern = Pattern.compile("^05\\d{9}$");
    Matcher telefonMatcher = telefonPattern.matcher(telefon);
    if (!telefonMatcher.matches()) {
        JOptionPane.showMessageDialog(null, "Telefon numarası 05 ile başlamalı ve 11 haneli olmalıdır!", "Hata!", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Adres regex kontrolü: en az 10 karakter olmalı
    Pattern adresPattern = Pattern.compile("^[a-zA-ZğüşıöçĞÜŞİÖÇ0-9 .,/]{10,}$");
    Matcher adresMatcher = adresPattern.matcher(adres);
    if (!adresMatcher.matches()) {
        JOptionPane.showMessageDialog(null, "Geçerli bir adres giriniz! (En az 10 karakter)", "Hata!", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Ürün sepete ekleniyor
    model.addElement(SepetListesi);
    
    // Sepetteki tüm ürünlerin toplamı hesaplanıyor
    double ToplamMiktar = 0;
    for (int i = 0; i < model.size(); i++) {
        String item = model.getElementAt(i);
        String[] parca = item.split("->");
        ToplamMiktar += Double.parseDouble(parca[1]);
    }
    
    // Toplam label güncelleniyor ve form sıfırlanıyor
    Toplamlabel.setText("Toplam:" + ToplamMiktar);
    AdetSpinner.setValue(1);
    OdemeYontemiComboBox.setSelectedIndex(0);
    HizliTeslimatCheckBox.setSelected(false);
    ToplamLabel.setText("Toplam: " + cicekfiyati + " ₺");
    }//GEN-LAST:event_SpeteEkleButtonActionPerformed

    private void SiparisiKaldirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiparisiKaldirButtonActionPerformed
        // JList'ten seçili ürün alınıyor
    String SeciliItem = (String) List.getSelectedValue();
    
    // Seçili ürün var mı kontrolü
    if (SeciliItem == null) {
        JOptionPane.showMessageDialog(null, "Lütfen bir ürün seçiniz!", "Hata!", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Kaldırma işlemi için kullanıcıdan onay alınıyor
    int onay = JOptionPane.showConfirmDialog(null, "Urunu Kaldirmak Istediginizden Eminmisiniz?", "Uyari", JOptionPane.YES_NO_OPTION);
    if (onay == JOptionPane.NO_OPTION) {
        return;
    }
    
    // Seçili ürün sepetten kaldırılıyor
    model.removeElement(SeciliItem);
    
    // Kalan ürünlerin toplamı yeniden hesaplanıyor
    double ToplamMiktar = 0;
    for (int i = 0; i < model.size(); i++) {
        String item = model.getElementAt(i);
        String[] parca = item.split("->");
        ToplamMiktar += Double.parseDouble(parca[1]);
    }
    
    // Toplam label güncelleniyor
    Toplamlabel.setText("Toplam:" + ToplamMiktar);
    }//GEN-LAST:event_SiparisiKaldirButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Çarpıya basılınca KatalogGörüntüleme ekranına geri dönülüyor
    this.dispose();
    KatalogGörüntüleme kataloggoruntule = new KatalogGörüntüleme(kullaniciAd, kullaniciId);
    kataloggoruntule.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SiparisOlusturma("", 0,0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AdetSpinner;
    private javax.swing.JLabel FiyatLabel;
    private javax.swing.JCheckBox HizliTeslimatCheckBox;
    private javax.swing.JList<String> List;
    private javax.swing.JComboBox<String> OdemeYontemiComboBox;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JLabel RenkveKategoriLabel;
    private javax.swing.JButton SipariTamamlaButton;
    private javax.swing.JButton SiparisiKaldirButton;
    private javax.swing.JButton SpeteEkleButton;
    private javax.swing.JTextField TelefonTextField;
    private javax.swing.JTextField TeslimatAdresiTextField;
    private javax.swing.JLabel ToplamLabel;
    private javax.swing.JLabel Toplamlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
