/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje2;

import javax.swing.JOptionPane;

/**
 *
 * @author awada
 */
public class UserAnaSayfa extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserAnaSayfa.class.getName());
    private String kullaniciAd;
    private int kullaniciId;

    /**
     * Creates new form AnaSayfa
     */
    public UserAnaSayfa(String ad, int kullaniciID) {
        initComponents();
        this.kullaniciAd = ad;
        //Anasayfada HosGeldiniz mesajini ve giris yapan kisinin adini gosterir
        HosGeldinizLabel.setText("Hoş Geldiniz " + ad + " - ID: " + kullaniciID);
        HosGeldinizLabel.setText("Hoş Geldiniz " + ad);
        this.kullaniciId = kullaniciID;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HosGeldinizLabel = new javax.swing.JLabel();
        KatalogGörüntülemeButton = new javax.swing.JButton();
        TeslimatBilgisi = new javax.swing.JButton();
        RaporuGoruntuleButton = new javax.swing.JButton();
        CikisYapButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        HosGeldinizLabel.setForeground(new java.awt.Color(0, 0, 0));
        HosGeldinizLabel.setText("Hos Geldiniz");

        KatalogGörüntülemeButton.setBackground(new java.awt.Color(0, 153, 153));
        KatalogGörüntülemeButton.setForeground(new java.awt.Color(0, 0, 0));
        KatalogGörüntülemeButton.setText("Katalog Goruntule");
        KatalogGörüntülemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KatalogGörüntülemeButtonActionPerformed(evt);
            }
        });

        TeslimatBilgisi.setBackground(new java.awt.Color(0, 153, 153));
        TeslimatBilgisi.setForeground(new java.awt.Color(0, 0, 0));
        TeslimatBilgisi.setText("Teslim Bilgisi");
        TeslimatBilgisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeslimatBilgisiActionPerformed(evt);
            }
        });

        RaporuGoruntuleButton.setBackground(new java.awt.Color(0, 153, 153));
        RaporuGoruntuleButton.setForeground(new java.awt.Color(0, 0, 0));
        RaporuGoruntuleButton.setText(" Raporu Goruntule");
        RaporuGoruntuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaporuGoruntuleButtonActionPerformed(evt);
            }
        });

        CikisYapButton.setBackground(new java.awt.Color(0, 153, 153));
        CikisYapButton.setForeground(new java.awt.Color(0, 0, 0));
        CikisYapButton.setText("Cikis Yap");
        CikisYapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CikisYapButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(HosGeldinizLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeslimatBilgisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RaporuGoruntuleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CikisYapButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KatalogGörüntülemeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(HosGeldinizLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KatalogGörüntülemeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TeslimatBilgisi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RaporuGoruntuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CikisYapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KatalogGörüntülemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KatalogGörüntülemeButtonActionPerformed

        // Katalog Görüntüleme ekranı açılıyor, kullanıcı adı ve id geçiriliyor
        KatalogGörüntüleme kataloggoruntuleme = new KatalogGörüntüleme(kullaniciAd, kullaniciId);
        kataloggoruntuleme.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KatalogGörüntülemeButtonActionPerformed

    private void TeslimatBilgisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeslimatBilgisiActionPerformed
        // Teslimat Bilgisi ekranı açılıyor, kullanıcı adı ve id geçiriliyor
        this.dispose();
        UserTeslimatBilgisi userTeslimatBilgisi = new UserTeslimatBilgisi(kullaniciAd, kullaniciId);
        userTeslimatBilgisi.setVisible(true);
    }//GEN-LAST:event_TeslimatBilgisiActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// Çarpıya basılınca kapanma engelleniyor, uyarı mesajı gösteriliyor
        JOptionPane.showMessageDialog(rootPane, "Cikis Yapmaniz lazim!", "Hata!", JOptionPane.ERROR_MESSAGE);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void CikisYapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CikisYapButtonActionPerformed
        // Çıkış yapmak istediğine dair onay alınıyor
        int onay = JOptionPane.showConfirmDialog(null, "Çıkış yapmak istediğinize emin misiniz?", "Çıkış", JOptionPane.YES_NO_OPTION);
        if (onay == JOptionPane.YES_OPTION) {
            // Onay verilirse Login ekranına dönülüyor
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_CikisYapButtonActionPerformed

    private void RaporuGoruntuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaporuGoruntuleButtonActionPerformed
        // Sipariş Raporu ekranı açılıyor, kullanıcı adı ve id geçiriliyor
        this.dispose();
        UserSipariRaporu usersiparisraporu = new UserSipariRaporu(kullaniciAd, kullaniciId);
        usersiparisraporu.setVisible(true);
    }//GEN-LAST:event_RaporuGoruntuleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserAnaSayfa("", 0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CikisYapButton;
    private javax.swing.JLabel HosGeldinizLabel;
    private javax.swing.JButton KatalogGörüntülemeButton;
    private javax.swing.JButton RaporuGoruntuleButton;
    private javax.swing.JButton TeslimatBilgisi;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
