/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje2;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author awada
 */
public class UserSipariRaporu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserSipariRaporu.class.getName());
    private String kullaniciAd;
    private int kullaniciId;

    /**
     * Creates new form UserSipariRaporu
     */
    public UserSipariRaporu(String ad, int kullaniciID) {
        initComponents();
        this.kullaniciAd = ad;
        this.kullaniciId = kullaniciID;
        RaporuYukle();
    }

    private void RaporuYukle() {
        try {
        // siparis_raporu.txt dosyası kontrol ediliyor
        File file = new File("siparis_raporu.txt");
        
        // Dosya yoksa bilgi mesajı gösteriliyor
        if (!file.exists()) {
            JOptionPane.showMessageDialog(null, "Henüz rapor oluşturulmamış!", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        // Dosya okumak için BufferedReader açılıyor
        BufferedReader reader = new BufferedReader(new FileReader(file));
        String line;
        StringBuilder kullaniciraporu = new StringBuilder();
        
        // Dosya satır satır okunuyor
        while ((line = reader.readLine()) != null) {
            
            // Satırda giriş yapan kullanıcının ID'si var mı kontrol ediliyor
            if (line.contains("[kullanici_id:" + kullaniciId + "]")) {
                
                // [kullanici_id:X] kısmı temizleniyor, TextArea'da görünmeyecek
                String Sonuc = line.replace("[kullanici_id:" + kullaniciId + "] ", "");
                kullaniciraporu.append(Sonuc).append("\n");
            }
        }
        reader.close();
        
        // Kullanıcıya ait satır bulunamadıysa bilgi mesajı gösteriliyor
        if (kullaniciraporu.length() == 0) {
            JOptionPane.showMessageDialog(null, "Sizin için oluşturulmuş rapor bulunamadı!", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Kullanıcıya ait rapor satırları TextArea'ya yazılıyor
            TextArea.setText(kullaniciraporu.toString());
        }
        
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "Dosya hatası: " + ex.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Çarpıya basılınca UserAnaSayfa'ya geri dönülüyor
    this.dispose();
    UserAnaSayfa useranasayfa = new UserAnaSayfa(kullaniciAd, kullaniciId);
    useranasayfa.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserSipariRaporu("",0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
