/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2proje2;

import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author awada
 */
public class ÇiçekEklemeDüzenleme extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ÇiçekEklemeDüzenleme.class.getName());
    private int seciliID = -1;
    private String kullaniciAd;
    private int kullaniciId;

    public ÇiçekEklemeDüzenleme(String Ad, int kullaniciID) {
        initComponents();
        this.kullaniciAd = Ad;
        this.kullaniciId = kullaniciID;
        TabloYukle();

    }
//DATABASE ILE FRAME ARASINDAKI BAGLANTIYI SAGLAYABILMEK ICIN BIR GETCONNECITON METODU

    private Connection getConnection() {
        Connection conn = null;
        try {

            conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/your_database",
    "your_username",
    "your_password"
            );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database connection error: " + ex.getMessage());
        }
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CicekAdiTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        KategoriComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        RenkComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        FiyatSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        StokSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        KesmeRadioButton = new javax.swing.JRadioButton();
        SaksiliRadioButton = new javax.swing.JRadioButton();
        DemetRadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        MevsimlikCheckBox = new javax.swing.JCheckBox();
        IthalCheckBox = new javax.swing.JCheckBox();
        KokuluCheckBox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AciklamaTextArea = new javax.swing.JTextArea();
        EkleButton = new javax.swing.JButton();
        GuncelleButton = new javax.swing.JButton();
        SilButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Panel.setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cicek Adi:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Kategori:");

        KategoriComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gül", "Lale", "Papatya", "Orkide" }));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Renk :");

        RenkComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sarı", "Kırmızı", "Beyaz", "Pembe", "Mavi", "Siyah" }));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fiyat:");

        FiyatSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Stok:");

        StokSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 0, 100, 1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tür:");

        buttonGroup1.add(KesmeRadioButton);
        KesmeRadioButton.setForeground(new java.awt.Color(51, 51, 51));
        KesmeRadioButton.setText("Kesme");
        KesmeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KesmeRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(SaksiliRadioButton);
        SaksiliRadioButton.setForeground(new java.awt.Color(51, 51, 51));
        SaksiliRadioButton.setText("Saksılı");

        buttonGroup1.add(DemetRadioButton);
        DemetRadioButton.setForeground(new java.awt.Color(51, 51, 51));
        DemetRadioButton.setText("Demet");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Özellikler:");

        MevsimlikCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        MevsimlikCheckBox.setText("Mevsimlik");

        IthalCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        IthalCheckBox.setText("Ithal");

        KokuluCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        KokuluCheckBox.setText("Kokulu");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Açıklama:");

        AciklamaTextArea.setBackground(new java.awt.Color(204, 204, 204));
        AciklamaTextArea.setColumns(20);
        AciklamaTextArea.setRows(5);
        jScrollPane1.setViewportView(AciklamaTextArea);

        EkleButton.setBackground(new java.awt.Color(51, 255, 51));
        EkleButton.setForeground(new java.awt.Color(0, 0, 0));
        EkleButton.setText("Ekle");
        EkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkleButtonActionPerformed(evt);
            }
        });

        GuncelleButton.setBackground(new java.awt.Color(255, 255, 0));
        GuncelleButton.setForeground(new java.awt.Color(0, 0, 0));
        GuncelleButton.setText("Güncelle");
        GuncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuncelleButtonActionPerformed(evt);
            }
        });

        SilButton.setBackground(new java.awt.Color(255, 51, 0));
        SilButton.setForeground(new java.awt.Color(0, 0, 0));
        SilButton.setText("Sil");
        SilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilButtonActionPerformed(evt);
            }
        });

        Table.setForeground(new java.awt.Color(0, 0, 0));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(CicekAdiTextField)
                            .addComponent(KategoriComboBox, 0, 165, Short.MAX_VALUE)
                            .addComponent(RenkComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FiyatSpinner)
                            .addComponent(StokSpinner))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(KesmeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SaksiliRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DemetRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addComponent(MevsimlikCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(IthalCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(KokuluCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(EkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GuncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(CicekAdiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(KategoriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(RenkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FiyatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StokSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KesmeRadioButton)
                    .addComponent(SaksiliRadioButton)
                    .addComponent(DemetRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MevsimlikCheckBox)
                    .addComponent(IthalCheckBox)
                    .addComponent(KokuluCheckBox))
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EkleButton)
                    .addComponent(GuncelleButton)
                    .addComponent(SilButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void TabloYukle() {
// JTable için boş bir model oluşturuluyor ve sütunlar ekleniyor
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Ad");
        model.addColumn("Kategori");
        model.addColumn("Renk");
        model.addColumn("Fiyat");
        model.addColumn("Stok");
        model.addColumn("Tur");

        // Veritabanı bağlantısı açılıyor
        Connection conn = getConnection();
        if (conn == null) {
            return;
        }

        try {
            Statement st = conn.createStatement();

            // Tüm çiçekler veritabanından çekiliyor
            String sql = "SELECT * FROM cicekler";
            ResultSet rs = st.executeQuery(sql);

            // Her satır tabloya ekleniyor
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("ad"),
                    rs.getString("kategori"),
                    rs.getString("renk"),
                    rs.getInt("fiyat"),
                    rs.getInt("stok"),
                    rs.getString("tur")
                });
            }

            // Model JTable'a bağlanıyor
            Table.setModel(model);
            st.close();
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Tablo yükleme hatası: " + ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void KesmeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KesmeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KesmeRadioButtonActionPerformed

    private void EkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkleButtonActionPerformed
// Formdan çiçek bilgileri alınıyor
        String ad = CicekAdiTextField.getText().trim();
        String kategori = KategoriComboBox.getSelectedItem().toString();
        String renk = RenkComboBox.getSelectedItem().toString();
        int fiyat = (int) FiyatSpinner.getValue();
        int stok = (int) StokSpinner.getValue();
        String aciklama = AciklamaTextArea.getText().trim();

        // Seçili RadioButton'a göre tür belirleniyor
        String tur = "";
        if (KesmeRadioButton.isSelected()) {
            tur = "Kesme";
        } else if (SaksiliRadioButton.isSelected()) {
            tur = "Saksılı";
        } else if (DemetRadioButton.isSelected()) {
            tur = "Demet";
        }

        // CheckBox değerleri alınıyor
        boolean mevsimlik = MevsimlikCheckBox.isSelected();
        boolean ithal = IthalCheckBox.isSelected();
        boolean kokulu = KokuluCheckBox.isSelected();

        // Çiçek adı boş alan kontrolü
        if (ad.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Çiçek adı boş olamaz!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Tür seçildi mi kontrolü
        if (tur.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tür seçiniz!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Çiçek adı regex kontrolü: sadece harf ve boşluk içermeli
        Pattern pattern = Pattern.compile("^[a-zA-ZğüşıöçĞÜŞİÖÇ ]+$");
        Matcher macther = pattern.matcher(ad);
        if (!macther.matches()) {
            JOptionPane.showMessageDialog(null, "Çiçek adı sadece harf içermelidir!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Veritabanı bağlantısı açılıyor
        Connection conn = getConnection();
        if (conn == null) {
            return;
        }

        try {
            Statement st = conn.createStatement();

            // Yeni çiçek veritabanına ekleniyor
            String sql = String.format("INSERT INTO cicekler(ad, kategori, renk, fiyat, stok, tur, mevsimlik, ithal, kokulu, aciklama) VALUES ('%s', '%s', '%s', %d, %d, '%s', %b, %b, %b, '%s')",
                    ad, kategori, renk, fiyat, stok, tur, mevsimlik, ithal, kokulu, aciklama);
            st.executeUpdate(sql);

            JOptionPane.showMessageDialog(null, "Çiçek başarıyla eklendi!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);

            // Tablo güncelleniyor ve form temizleniyor
            TabloYukle();
            CicekAdiTextField.setText("");
            FiyatSpinner.setValue(0);
            StokSpinner.setValue(0);
            AciklamaTextArea.setText("");
            MevsimlikCheckBox.setSelected(false);
            IthalCheckBox.setSelected(false);
            KokuluCheckBox.setSelected(false);

            st.close();
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Hata: " + ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EkleButtonActionPerformed

    private void GuncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuncelleButtonActionPerformed
        // Tabloda seçili bir çiçek var mı kontrolü, -1 ise seçili yok demek
        if (seciliID == -1) {
            JOptionPane.showMessageDialog(null, "Lütfen bir çiçek seçiniz!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Formdan güncellenecek çiçek bilgileri alınıyor
        String ad = CicekAdiTextField.getText().trim();
        String kategori = KategoriComboBox.getSelectedItem().toString();
        String renk = RenkComboBox.getSelectedItem().toString();
        int fiyat = (int) FiyatSpinner.getValue();
        int stok = ((Number) StokSpinner.getValue()).intValue();
        String aciklama = AciklamaTextArea.getText().trim();

        // Seçili RadioButton'a göre tür belirleniyor
        String tur = "";
        if (KesmeRadioButton.isSelected()) {
            tur = "Kesme";
        } else if (SaksiliRadioButton.isSelected()) {
            tur = "Saksılı";
        } else if (DemetRadioButton.isSelected()) {
            tur = "Demet";
        }

        // CheckBox değerleri alınıyor
        boolean mevsimlik = MevsimlikCheckBox.isSelected();
        boolean ithal = IthalCheckBox.isSelected();
        boolean kokulu = KokuluCheckBox.isSelected();

        // Çiçek adı boş alan kontrolü
        if (ad.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Çiçek adı boş olamaz!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Tür seçildi mi kontrolü
        if (tur.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tür seçiniz!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Çiçek adı regex kontrolü: sadece harf ve boşluk içermeli
        Pattern pattern = Pattern.compile("^[a-zA-ZğüşıöçĞÜŞİÖÇ ]+$");
        Matcher matcher = pattern.matcher(ad);
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(null, "Çiçek adı sadece harf içermelidir!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Veritabanı bağlantısı açılıyor
        Connection conn = getConnection();
        if (conn == null) {
            return;
        }

        try {
            Statement st = conn.createStatement();

            // Seçili çiçek veritabanında güncelleniyor
            String sql = String.format(Locale.US, "UPDATE cicekler SET ad='%s', kategori='%s', renk='%s', fiyat=%d, stok=%d, tur='%s', mevsimlik=%b, ithal=%b, kokulu=%b, aciklama='%s' WHERE id=%d",
                    ad, kategori, renk, fiyat, stok, tur, mevsimlik, ithal, kokulu, aciklama, seciliID);
            st.executeUpdate(sql);

            JOptionPane.showMessageDialog(null, "Çiçek güncellendi!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);

            // Tablo güncelleniyor ve seçili ID sıfırlanıyor
            TabloYukle();
            seciliID = -1;
            st.close();
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Hata: " + ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GuncelleButtonActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
// Tıklanan satırın indeksi alınıyor
        int row = Table.getSelectedRow();

        if (row != -1) {
            // Seçili çiçeğin ID'si saklanıyor, güncelle/sil işlemlerinde kullanılacak
            seciliID = (int) Table.getValueAt(row, 0);

            // Tablodaki veriler forma aktarılıyor
            CicekAdiTextField.setText(Table.getValueAt(row, 1).toString());
            KategoriComboBox.setSelectedItem(Table.getValueAt(row, 2).toString());
            RenkComboBox.setSelectedItem(Table.getValueAt(row, 3).toString());
            FiyatSpinner.setValue(Table.getValueAt(row, 4));
            StokSpinner.setValue(Table.getValueAt(row, 5));

            // Tür bilgisine göre ilgili RadioButton seçili yapılıyor
            String tur = Table.getValueAt(row, 6).toString();
            if (tur.equals("Kesme")) {
                KesmeRadioButton.setSelected(true);
            } else if (tur.equals("Saksılı")) {
                SaksiliRadioButton.setSelected(true);
            } else if (tur.equals("Demet")) {
                DemetRadioButton.setSelected(true);
            }
        }

        // Veritabanı bağlantısı açılıyor
        Connection conn = getConnection();
        if (conn == null) {
            return;
        }

        try {
            Statement st = conn.createStatement();

            // Tabloda görünmeyen özellikler DB'den çekiliyor
            String sql = String.format("SELECT mevsimlik, ithal, kokulu, aciklama FROM cicekler WHERE id = %d", seciliID);
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                // CheckBox ve TextArea değerleri DB'den gelen verilerle güncelleniyor
                MevsimlikCheckBox.setSelected(rs.getBoolean("mevsimlik"));
                IthalCheckBox.setSelected(rs.getBoolean("ithal"));
                KokuluCheckBox.setSelected(rs.getBoolean("kokulu"));
                AciklamaTextArea.setText(rs.getString("aciklama"));
            }
            st.close();
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Hata: " + ex.getMessage());
        }
    }//GEN-LAST:event_TableMouseClicked

    private void SilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilButtonActionPerformed
        // Tabloda seçili bir çiçek var mı kontrolü, -1 ise seçili yok demek
        if (seciliID == -1) {
            JOptionPane.showMessageDialog(null, "Lütfen bir çiçek seçiniz!", "Hata!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Silme işlemi için kullanıcıdan onay alınıyor
        int confirm = JOptionPane.showConfirmDialog(null, "Bu çiçeği silmek istediğinize emin misiniz?", "Onay", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.NO_OPTION) {
            return;
        }

        // Veritabanı bağlantısı açılıyor
        Connection conn = getConnection();
        if (conn == null) {
            return;
        }

        try {
            Statement st = conn.createStatement();

            // Seçili çiçek veritabanından siliniyor
            String sql = String.format("DELETE FROM cicekler WHERE id=%d", seciliID);
            st.executeUpdate(sql);

            // Tablo güncelleniyor, seçili ID sıfırlanıyor ve form temizleniyor
            TabloYukle();
            seciliID = -1;
            CicekAdiTextField.setText("");
            FiyatSpinner.setValue(0.0);
            StokSpinner.setValue(0);
            AciklamaTextArea.setText("");
            MevsimlikCheckBox.setSelected(false);
            IthalCheckBox.setSelected(false);
            KokuluCheckBox.setSelected(false);

            st.close();
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Hata: " + ex.getMessage(), "Hata!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_SilButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Çarpıya basılınca AdminAnaSayfa'ya geri dönülüyor
        this.dispose();
        AdminAnaSayfa adminAnaSayfa = new AdminAnaSayfa(kullaniciAd, kullaniciId);
        adminAnaSayfa.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ÇiçekEklemeDüzenleme("", 0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AciklamaTextArea;
    private javax.swing.JTextField CicekAdiTextField;
    private javax.swing.JRadioButton DemetRadioButton;
    private javax.swing.JButton EkleButton;
    private javax.swing.JSpinner FiyatSpinner;
    private javax.swing.JButton GuncelleButton;
    private javax.swing.JCheckBox IthalCheckBox;
    private javax.swing.JComboBox<String> KategoriComboBox;
    private javax.swing.JRadioButton KesmeRadioButton;
    private javax.swing.JCheckBox KokuluCheckBox;
    private javax.swing.JCheckBox MevsimlikCheckBox;
    private javax.swing.JPanel Panel;
    private javax.swing.JComboBox<String> RenkComboBox;
    private javax.swing.JRadioButton SaksiliRadioButton;
    private javax.swing.JButton SilButton;
    private javax.swing.JSpinner StokSpinner;
    private javax.swing.JTable Table;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
